### PR TITLE
test: GitHub workflow added for db tests

### PR DESCRIPTION
**Pull request by hamees-sayed**

### CODE REVIEW

**Comment by hamees-sayed** [comment]
lord have mercy

**Comment by hamees-sayed** [comment]
@Shivansh-yadav13 the test is failing because there's no `sqlite_database/data.db` in the repo. And I'm still not getting this semantic PR thing, did follow their guidelines for my commit message

**Comment by Shivansh-yadav13** [comment]
> 3.) To start the project locally we need to create a sqlite file with name as data.db. Navigate to the root of the project and create a folder with the name sqlite_database and inside it create a file data.db.

@hamees-sayed as mentioned in readme for testing purposes we will have to setup sqlite_database/data.db for running the tests

**Comment by hamees-sayed** [comment]
@Shivansh-yadav13 yes the tests are passing locally but I've unstaged the `sqlite_database` while creating the PR, is that the reason for the failing test here? Am I supposed to raise the PR along with the `sqlite_database` folder, I'm not very familiar with github actions.

**Comment by wliao008** [comment]
@hamees-sayed you can probably create the db file right before you run the test, something like this:

```
   - name: Test             
      run: touch /app/sqlite_database/data.db && go test -v ./...
```

**Comment by Shivansh-yadav13** [comment]
@hamees-sayed 
Also you dont need to merge latest changes since there is no conflict in branch
Screenshot from 2022-10-07 15-03-24

**Comment by wliao008** [comment]
@hamees-sayed i see that the tests still failed, and looking at the database_test.go I realized it's looking for the db file in its working directory, not the absolute path `/app` that's used by the container. So give this a try instead hopefully it works:

```
 - name: Test             
    run: touch sqlite_database/data.db && go test -v ./...
```

**Review by Shivansh-yadav13 — CHANGES_REQUESTED** [review]

**Comment by hamees-sayed** [comment]
alright, will check on this 👍

**Comment by Shivansh-yadav13** [comment]
@hamees-sayed can you commit the changes suggested above then I will merge it, need this workflow for testing other PRs 😅

**Comment by hamees-sayed** [comment]
finally lol

**Comment by hamees-sayed** [comment]
why is the semantic pr failing, the commit message is in accordance with their guidelines right?

**Comment by Shivansh-yadav13** [comment]
> why is the semantic pr failing, the commit message is in accordance with their guidelines right?

It is becuase one of them is not but it's okay for now I will squash and merge it.
Screenshot from 2022-10-12 14-51-33

**Pull request merged**
