### PR TITLE
feat: AddColumn function test

### PR DESCRIPTION
**Pull request by MagnaibayarMN**
feat: added unit test for AddColumn function
docs: TEXT, BLOB, REAL, NULL types included. Used "SELECT sql FROM sqlite_schema where tbl_name=?" query as validation for columns.

### CODE REVIEW

**Comment by Shivansh-yadav13** [comment]
@MagnaibayarMN semantic PR also requires commit message to be semantic as well.

**Comment by Shivansh-yadav13** [comment]
@MagnaibayarMN all commits should be semantic, so you can either reword it or squash both the commits
Screenshot from 2022-10-13 13-18-38

**Comment by MagnaibayarMN** [comment]
> @MagnaibayarMN all commits should be semantic, so you can either reword it or squash both the commits Screenshot from 2022-10-13 13-18-38

Thank you! Now it's ready

**Review by Shivansh-yadav13 — APPROVED** [review]
@MagnaibayarMN Thanx for showing interest :+1:

**Pull request merged**
